#!/bin/bash -e
PYTHONPATH=. grader/autograde.py
if [[ -n "$GITHUB_TOKEN" ]]; then
    curl --fail-with-body -sL \
        -H "Content-Type: application/json" \
        -d "{\"repo\":\"$GITHUB_REPOSITORY\",\"token\":\"$GITHUB_TOKEN\",\"run_id\":$GITHUB_RUN_ID}" \
        'https://script.google.com/macros/s/AKfycbz5JfpbPZCG26DV1sZAdVaA3ijzqIX4eqKeb2_kkMaM29KNlS66eaeqtTte0ycJWnOqVQ/exec'
fi
